"""initial_schema

Revision ID: 146f394e068a
Revises: 
Create Date: 2026-06-21 21:00:18.534596
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '146f394e068a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=100), nullable=False),
    sa.Column('rack', sa.String(length=20), nullable=False),
    sa.Column('shelf', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("location_code ~ '^[A-Z0-9]+-[A-Z0-9]+-[A-Z0-9]+-[A-Z0-9]+$'", name='chk_locations_code_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_code')
    )
    op.create_index('idx_locations_location_code', 'locations', ['location_code'], unique=False)
    op.create_index('idx_locations_warehouse_name', 'locations', ['warehouse_name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("TRIM(name) <> ''", name='chk_roles_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("TRIM(name) <> ''", name='chk_sections_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(username)) >= 3', name='chk_users_username_len'),
    sa.CheckConstraint('LENGTH(password_hash) >= 60', name='chk_users_password_len'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'UPLOAD_DOCUMENT', 'OPEN_DOCUMENT', 'ARCHIVE_DOCUMENT', 'MOVE_ITEM', 'ADD_ITEM', 'REMOVE_ITEM', 'CREATE_LOCATION', 'CREATE_ITEM', 'SEARCH_ITEM', 'VIEW_HISTORY', 'GRANT_ACCESS', 'REVOKE_ACCESS', name='audit_action_enum'), nullable=False),
    sa.Column('module', sa.Enum('IAM', 'SOP', 'WAREHOUSE', 'SYSTEM', name='audit_module_enum'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_module', 'audit_logs', ['module'], unique=False)
    op.create_index('idx_audit_logs_target_id', 'audit_logs', ['target_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Auto-assigned integer version (1, 2, 3…)'),
    sa.Column('version_label', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Path relative to UPLOAD_ROOT — never the absolute OS path'),
    sa.Column('file_name', sa.String(length=512), nullable=False, comment='Original filename as uploaded'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'ARCHIVED', 'REJECTED', name='document_status_enum'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("TRIM(file_path) <> ''", name='chk_documents_filepath_not_empty'),
    sa.CheckConstraint("TRIM(title) <> ''", name='chk_documents_title_not_empty'),
    sa.CheckConstraint('version_number >= 1', name='chk_documents_version_positive'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'section_id', 'version_number', name='uq_documents_title_section_version')
    )
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_is_deleted', 'documents', ['is_deleted'], unique=False)
    op.create_index('idx_documents_section_deleted_status', 'documents', ['section_id', 'is_deleted', 'status'], unique=False)
    op.create_index('idx_documents_section_id', 'documents', ['section_id'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=20), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'CONSUMED', 'DAMAGED', 'QUARANTINE', name='item_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("item_code ~ '^[A-Z]{2}-\\d{6}$'", name='chk_items_code_format'),
    sa.CheckConstraint('quantity >= 0', name='chk_items_quantity_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_index('idx_items_created_by', 'items', ['created_by'], unique=False)
    op.create_index('idx_items_item_code', 'items', ['item_code'], unique=False)
    op.create_index('idx_items_location_id', 'items', ['location_id'], unique=False)
    op.create_index('idx_items_status', 'items', ['status'], unique=False)
    op.create_table('user_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('permission_level', sa.Enum('READ', 'WRITE', 'ADMIN', name='permission_level_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id', name='uq_user_sections_user_section')
    )
    op.create_index('idx_user_sections_section_id', 'user_sections', ['section_id'], unique=False)
    op.create_index('idx_user_sections_user_id', 'user_sections', ['user_id'], unique=False)
    op.create_table('movement_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('from_location', sa.UUID(), nullable=True),
    sa.Column('to_location', sa.UUID(), nullable=False),
    sa.Column('moved_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_location IS NULL OR from_location <> to_location', name='chk_movement_logs_different_locations'),
    sa.ForeignKeyConstraint(['from_location'], ['locations.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location'], ['locations.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movement_logs_created_at', 'movement_logs', ['created_at'], unique=False)
    op.create_index('idx_movement_logs_item_id', 'movement_logs', ['item_id'], unique=False)
    op.create_index('idx_movement_logs_moved_by', 'movement_logs', ['moved_by'], unique=False)
    op.create_index('idx_movement_logs_to_location', 'movement_logs', ['to_location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movement_logs_to_location', table_name='movement_logs')
    op.drop_index('idx_movement_logs_moved_by', table_name='movement_logs')
    op.drop_index('idx_movement_logs_item_id', table_name='movement_logs')
    op.drop_index('idx_movement_logs_created_at', table_name='movement_logs')
    op.drop_table('movement_logs')
    op.drop_index('idx_user_sections_user_id', table_name='user_sections')
    op.drop_index('idx_user_sections_section_id', table_name='user_sections')
    op.drop_table('user_sections')
    op.drop_index('idx_items_status', table_name='items')
    op.drop_index('idx_items_location_id', table_name='items')
    op.drop_index('idx_items_item_code', table_name='items')
    op.drop_index('idx_items_created_by', table_name='items')
    op.drop_table('items')
    op.drop_index('idx_documents_uploaded_by', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_section_id', table_name='documents')
    op.drop_index('idx_documents_section_deleted_status', table_name='documents')
    op.drop_index('idx_documents_is_deleted', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_target_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_module', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('sections')
    op.drop_table('roles')
    op.drop_index('idx_locations_warehouse_name', table_name='locations')
    op.drop_index('idx_locations_location_code', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
