"""document_sections_m2m

Revision ID: fe9a04227891
Revises: 66e35eb4e93a
Create Date: 2026-06-22 05:14:04.591774
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe9a04227891'
down_revision: Union[str, None] = '66e35eb4e93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sections',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'section_id')
    )
    
    # ── Migrate Data ────────────────────────────────────────────────────────
    op.execute(
        "INSERT INTO document_sections (document_id, section_id) "
        "SELECT id, section_id FROM documents"
    )
    
    op.drop_index(op.f('idx_documents_section_deleted_status'), table_name='documents')
    op.drop_index(op.f('idx_documents_section_id'), table_name='documents')
    op.drop_constraint('uq_documents_title_section_version', 'documents', type_='unique')
    op.create_unique_constraint('uq_documents_title_version', 'documents', ['title', 'version_number'])
    op.drop_constraint('documents_section_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'section_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('documents_section_id_fkey'), 'documents', 'sections', ['section_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('uq_documents_title_version', 'documents', type_='unique')
    op.create_unique_constraint(op.f('uq_documents_title_section_version'), 'documents', ['title', 'section_id', 'version_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_documents_section_id'), 'documents', ['section_id'], unique=False)
    op.create_index(op.f('idx_documents_section_deleted_status'), 'documents', ['section_id', 'is_deleted', 'status'], unique=False)
    op.drop_table('document_sections')
    # ### end Alembic commands ###
